[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true 
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
mainnet = "https://lb.drpc.org/ethereum/Avduh2iIjEAksBUYtd4wP1NUPObEnwYR76WEFhW5UfFk"
sepolia = "https://lb.drpc.org/sepolia/Avduh2iIjEAksBUYtd4wP1NUPObEnwYR76WEFhW5UfFk"
holesky = "https://lb.drpc.org/holesky/Avduh2iIjEAksBUYtd4wP1NUPObEnwYR76WEFhW5UfFk"

[etherscan]
mainnet = { key = "2DTB79CHTEJ6PEDCTEINC8GV3IHUXHGP9A" }
goerli = { key = "2DTB79CHTEJ6PEDCTEINC8GV3IHUXHGP9A" }
holesky = { key = "2DTB79CHTEJ6PEDCTEINC8GV3IHUXHGP9A" }